services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: backend
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: astro-app/Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
